apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  labels:
    app.kubernetes.io/name: exporter
    app.kubernetes.io/component: node-exporter
spec:
  selector:
      app.kubernetes.io/name: exporter
      app.kubernetes.io/component: node-exporter
  ports:
    - name: node-exporter
      protocol: TCP
      port: 9100
      targetPort: 9100
