version: "3.9"

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.45.0
    command: ["--config=/conf/config.yaml"]
    configs:
      - source: otel-config
        target: /conf/config.yaml
    environment:
      OTEL_RESOURCE_ATTRIBUTES: host.name={{.Node.Hostname}},os.type={{.Node.Platform.OS}}
    ports:
      - "4317:4317"     # OTLP gRPC receiver
      - "4318:4318"     # OTLP HTTP receiver
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 2000m

configs:
  otel-config:
    file: ./config.yaml
