## List of configuration settings
## for prometheus deployment
prometheus:
  image:
    repository: quay.io/prometheus/prometheus
    tag: v2.31.1
    pullPolicy: IfNotPresent

  port: 9090
  serviceType: ClusterIP

  ## targetsCount defines how many copies of nodeexporter
  ## to add as scrape targets.
  ## affects metrics volume and cardinality
  targetsCount: 200

  ## defines how frequently scrape targets
  scrapeInterval: 10s

  ## remote-write configurations for prometheus
  ## prometheus will replicate data to all configured URLs
  remoteWrite:
      ## single-node: http://<remote-addr>:8428/api/v1/write
      ## cluster: http://<remote-insert-addr>:8480/insert/0/prometheus/
    - url: ""
      ## auth token for remote.
      ## leave empty if no token configured
      token: ""

  ## Prometheus data retention period (default if not specified is 15 days)
  retention: "15d"

  persistence:
    # -- Enable persistence using PVC.
    enabled: true
    # -- PVC Storage Request for Prometheus data volume.
    size: 5Gi

  resources:
    limits:
      cpu: 2400m
      memory: 10Gi
    requests:
      cpu: 1
      memory: 5Gi

  nodeSelector: { }
  affinity: { }
  tolerations: [ ]

  securityContext:
    runAsUser: 65534
    runAsNonRoot: true
    runAsGroup: 65534
    fsGroup: 65534


## List of configuration settings
## for nginx + nodeexporter deployment
nodeExporter:
  image:
    repository: prom/node-exporter
    pullPolicy: IfNotPresent
    tag: "v1.3.1"

  ## Security context to be added to node-exporter pods
  ##
  securityContext:
    fsGroup: 65534
    runAsGroup: 65534
    runAsNonRoot: true
    runAsUser: 65534

  resources:
    limits:
      cpu: 500m
      memory: 700Mi
    requests:
      cpu: 100m
      memory: 100Mi
  
  nginxResources:
    limits:
      cpu: 1
      memory: 1700Mi
    requests:
      cpu: 500m
      memory: 500Mi

  nodeSelector: { }
  affinity: { }
  tolerations: [ ]

  ## port for nodeexporter to run
  hostPort: 9101
  ## port for nginx to run
  ## prometheus will use this port for scraping
  hostPortCached: 9102
