apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-exporter
  labels:
    app.kubernetes.io/name: exporter
    app.kubernetes.io/component: node-exporter
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: exporter
      app.kubernetes.io/component: node-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: exporter
        app.kubernetes.io/component: node-exporter
    spec:
      containers:
        - name: nodeexporter
          image: "prom/node-exporter:v1.3.1"
          imagePullPolicy: "IfNotPresent"
          args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --path.rootfs=/host/root
            - --no-collector.wifi
            - --no-collector.hwmon
            - --no-collector.time
            - --no-collector.timex
            - --no-collector.arp
            - --no-collector.netdev
            - --no-collector.netstat
            - --collector.processes
            - --web.max-requests=40
            - --web.listen-address=:9101
          ports:
            - name: metrics
              containerPort: 9101
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: proc
              mountPath: /host/proc
