apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: default
  labels:
    app.kubernetes.io/name: exporter
    app.kubernetes.io/component: node-exporter
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: exporter
    app.kubernetes.io/component: node-exporter
  ports:
    - port: 9101
      name: exporter
      targetPort: 9101
    - port: 9102
      name: proxy
      targetPort: 9102
