apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app.kubernetes.io/name: opentelemetry
    app.kubernetes.io/component: otel-collector
spec:
  type: ClusterIP
  selector:
      app.kubernetes.io/name: opentelemetry
      app.kubernetes.io/component: otel-collector
  ports:
    - name: otel-collector
      protocol: TCP
      port: 8889
      targetPort: 8889
