apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "vm-benchmark.fullname" . }}-prometheus-cm
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "vm-benchmark.prometheus.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.scrapeInterval }}
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ['localhost:{{ .Values.prometheus.port }}']
      - job_name: node_exporter
        static_configs:
    {{- $svc :=  include "vm-benchmark.nginxCached" .  }}
    {{- $count := .Values.prometheus.targetsCount | int }}
    {{- range until $count }}
         - targets: ['{{ $svc }}']
           labels:
             host_number: cfg_{{.}}
    {{- end }}
