apiVersion: v1
kind: Service
metadata:
  name: {{ include "vm-benchmark.fullname" . }}-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vm-benchmark.prometheus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.prometheus.serviceType }}
  selector:
    {{- include "vm-benchmark.prometheus.selectorLabels" . | nindent 6 }}
  ports:
    - port: {{ .Values.prometheus.port }}
      name: prometheus
      targetPort: {{ .Values.prometheus.port }}
