version: "3.3"

services:
  otel-collector:
    image: signoz/otelcontribcol:0.43.0
    command: ["--config=/conf/config.yaml"]
    volumes:
      - ./config.yaml:/conf/config.yaml
    environment:
      OTEL_RESOURCE_ATTRIBUTES: node_hostname=test-instance,service_name=otel-collector
    ports:
      - "4317:4317"     # OTLP gRPC receiver
      - "4318:4318"     # OTLP HTTP receiver
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 2000m
