version: "3.3"

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.45.0
    command: ["--config=/conf/config.yaml"]
    volumes:
      - ./config.yaml:/conf/config.yaml
    # environment:
    #   OTEL_RESOURCE_ATTRIBUTES: host.name=test-instance,os.type=linux
    ports:
      - "4317:4317"     # OTLP gRPC receiver
      - "4318:4318"     # OTLP HTTP receiver
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 2000m
